apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jerney.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
{{ include "jerney.labels" . | indent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: {{ .Values.backend.port | quote }}
            - name: DB_HOST
              # value: {{ .Values.postgres.name }}
              value: {{ .Values.externalDatabase.host | quote }}
            - name: DB_PORT
              value: {{ .Values.externalDatabase.port | quote }}
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.externalDatabase.name }}-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  # name: {{ .Values.externalDatabase.name }}-secret
                  name: {{ default (printf "%s-secret" .Values.externalDatabase.name) .Values.externalDatabase.existingSecret }}
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.externalDatabase.name }}-config
                  key: POSTGRES_DB
            - name: PGSSLMODE
              value: require
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"

          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
{{ toYaml .Values.backend.resources | indent 12 }}

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jerney.labels" . | indent 4 }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}