{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jerney.labels" . | indent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    # kind: SecretStore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalDatabase.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.awsSecretName }}
        property: POSTGRES_PASSWORD
{{- end }}
