{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jerney-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jerney.labels" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow ALB / external traffic to frontend on port 80
    - ports:
        - protocol: TCP
          port: {{ .Values.frontend.port }}

    # Allow frontend -> backend
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.port }}

    # Allow backend -> postgres
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.externalDatabase.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.externalDatabase.port }}

  egress:
    # Allow frontend -> backend
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.backend.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.port }}

    # Allow backend -> postgres
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.externalDatabase.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.externalDatabase.port }}

    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
