apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
