apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.externalDatabase.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jerney.labels" . | indent 4 }}
data:
  POSTGRES_USER: {{ .Values.externalDatabase.user | quote }}
  POSTGRES_DB: {{ .Values.externalDatabase.database | quote }}