apiVersion: v1
kind: Service
metadata:
  name: jerney-postgres
  namespace: jerney
spec:
  clusterIP: None
  selector:
    app: jerney-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jerney-postgres
  namespace: jerney
spec:
  serviceName: jerney-postgres
  replicas: 1
  selector:
    matchLabels:
      app: jerney-postgres
  template:
    metadata:
      labels:
        app: jerney-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - name: postgres
              containerPort: 5432

          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata

          envFrom:
            - configMapRef:
                name: jerney-postgres-config
            - secretRef:
                name: jerney-postgres-secret

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - jerney_user
                - -d
                - jerney_db
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: jerney-ebs-gp3
        resources:
          requests:
            storage: 5Gi
