postgres:
  name: jerney-pg
  image: postgres:16-alpine
  user: jerney_user
  password: jerney_pass_2026x
  database: jerney_db
  port: 5432
  storage:
    className: jerney-ebs-gp3
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

storageClass:
  enabled: true
  name: jerney-ebs-gp3
  type: gp3
  encrypted: "true"
  reclaimPolicy: Retain

backend:
  name: jerney-backend
  image: 865274826587.dkr.ecr.us-east-1.amazonaws.com/jerney-backend:v1
  replicas: 1
  port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

frontend:
  name: jerney-frontend
  image: 865274826587.dkr.ecr.us-east-1.amazonaws.com/jerney-frontend:v2
  replicas: 1
  port: 80
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: alb
  host: "jerney.44.208.196.100.nip.io"

networkPolicy:
  enabled: true