namespace: jerney

postgres:
  name: jerney-postgres
  image: postgres:16-alpine
  user: jerney_user
  password: jerney_pass_2026
  database: jerney_db
  port: 5432
  storage:
    className: jerney-ebs-gp3
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

storageClass:
  enabled: true
  name: jerney-ebs-gp3
  type: gp3
  encrypted: "true"
  reclaimPolicy: Retain

backend:
  name: jerney-backend
  image: 865274826587.dkr.ecr.us-east-1.amazonaws.com/jerney-backend:v1
  replicas: 1
  port: 5000

frontend:
  name: jerney-frontend
  image: 865274826587.dkr.ecr.us-east-1.amazonaws.com/jerney-frontend:v2
  replicas: 1
  port: 80
  serviceType: LoadBalancer
